---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/auth/login":
    post:
      summary: Realiza o login do usuário
      tags:
      - Autenticação
      parameters: []
      responses:
        '200':
          description: login realizado com sucesso
        '401':
          description: credenciais inválidas
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/autismia":
    get:
      summary: Lista todas as AutismIA
      tags:
      - AutismIA
      security:
      - bearerAuth: []
      responses:
        '200':
          description: AutismIA listadas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    endereco:
                      type: string
                    telefone:
                      type: string
                    email:
                      type: string
                    responsavel:
                      type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
